//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentasmensajes
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaVisualizacion { get; set; }
        public Nullable<int> MensajeId { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public string UsuarioId { get; set; }
    
        public virtual aspnetusers aspnetusers { get; set; }
        public virtual cuentas cuentas { get; set; }
        public virtual mensajes mensajes { get; set; }
    }
}
