//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Referencia { get; set; }
        public string DimensionesCabina { get; set; }
        public string DimensionesHueco { get; set; }
        public string CargaNominal { get; set; }
        public string Velocidad { get; set; }
        public string Recorrido { get; set; }
        public string Paradas { get; set; }
        public string Accesos { get; set; }
        public string VoltajeDeRed { get; set; }
        public string PotenciaDeMaquina { get; set; }
        public string TipoDeManiobra { get; set; }
        public string NumeroDeGuayas { get; set; }
        public string Fotografia { get; set; }
        public string Plano { get; set; }
        public int obra_id { get; set; }
        public Nullable<int> CantidadPersonas { get; set; }
    }
}
