//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class fallas
    {
        public int Id { get; set; }
        public System.DateTime FechaFalla { get; set; }
        public string Obra { get; set; }
        public string Equipo { get; set; }
        public string Tipo { get; set; }
        public string Componente { get; set; }
        public string Personal { get; set; }
        public string StatusFalla { get; set; }
        public Nullable<System.DateTime> FechaSolucion { get; set; }
        public string NumeroReporte { get; set; }
        public string Descripcion { get; set; }
        public string Condicion { get; set; }
        public string AccionesTomadas { get; set; }
        public string AccionesRecomendadas { get; set; }
        public string Duracion { get; set; }
        public string PersonaReporte { get; set; }
        public string GerenciaResponsable { get; set; }
        public Nullable<int> obra_id { get; set; }
    }
}
