//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class herramientas
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string Propiedad { get; set; }
        public Nullable<System.DateTime> FechaCulminacion { get; set; }
        public string CantidadDeposito { get; set; }
        public Nullable<System.DateTime> FechaEntrada { get; set; }
        public string SupervisorObra { get; set; }
        public string TecnicoResponsable { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> previo_id { get; set; }
        public int obra_id { get; set; }
        public string Archivo { get; set; }
        public string obra { get; set; }
    }
}
