//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantenimientocorrectivo
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public string PersonaJuridica { get; set; }
        public Nullable<System.DateTime> FechaVisita { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public string NombreDocumento { get; set; }
        public string Tecnico { get; set; }
        public string EquiposAtendidos { get; set; }
        public string StatusMantenimiento { get; set; }
        public string Archivo { get; set; }
        public string Evaluacion { get; set; }
        public string HoraLlegada { get; set; }
        public string HoraSalida { get; set; }
        public Nullable<int> IdVenta { get; set; }
    }
}
