//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class obrasgestion
    {
        public int Id { get; set; }
        public string primercontacto { get; set; }
        public string contactotelefonicoobra { get; set; }
        public string correoelectronicoobra { get; set; }
        public string cargoobra { get; set; }
        public string nombreconstructora { get; set; }
        public string contactotelefonicoempresa { get; set; }
        public string correoelectronicoempresa { get; set; }
        public string cargoempresa { get; set; }
        public string ubicacionobra { get; set; }
        public string tipoobra { get; set; }
        public string numeroequipos { get; set; }
        public string tipoequipo { get; set; }
        public string vendidasclimb { get; set; }
        public string vendidasotros { get; set; }
        public string novendidas { get; set; }
        public string paralizadas { get; set; }
        public string direccionoficina { get; set; }
        public string Descripcion { get; set; }
    }
}
