//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class obras
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string PersonaJuridica { get; set; }
        public string DireccionFacturacion { get; set; }
        public string DireccionOficina { get; set; }
        public string DireccionObra { get; set; }
        public string TelefonoOficina { get; set; }
        public string Contacto { get; set; }
        public string Contacto2 { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string foto { get; set; }
        public string mapa { get; set; }
        public string oficina { get; set; }
    }
}
