//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class previos
    {
        public int Id { get; set; }
        public System.DateTime FechaFirmaContrato { get; set; }
        public System.DateTime FechaPagoInicialFabrica { get; set; }
        public System.DateTime FechaPagoInicialEquipo { get; set; }
        public System.DateTime FechaConstruccion { get; set; }
        public System.DateTime FechaSalidaFabrica { get; set; }
        public System.DateTime FechaSalidaBuque { get; set; }
        public System.DateTime FechaLlegadaBuque { get; set; }
        public System.DateTime FechaPeriodoNacionalizacion { get; set; }
        public System.DateTime FechaSalidaPuertoObra { get; set; }
        public System.DateTime FechaDescargaResguardo { get; set; }
        public string ActivacionProtocoloGarantiaFabrica { get; set; }
        public System.DateTime FechaInicioMontaje { get; set; }
        public System.DateTime FechaEntregaSoso { get; set; }
        public System.DateTime FechaCulminacionMontaje { get; set; }
        public System.DateTime FechaConfiguracion { get; set; }
        public System.DateTime FechaPeriodoPrueba { get; set; }
        public System.DateTime FechaInspeccion { get; set; }
        public string TecnicoInstalador { get; set; }
        public string InformeEntregaFinal { get; set; }
        public string FechaDescargaResguardoFotografia { get; set; }
        public string FechaCulminacionMontajeFotografia { get; set; }
        public string FechaInspeccionFotografia { get; set; }
        public string FechaInspeccionVideo { get; set; }
        public int equipo_id { get; set; }
        public string FechaFirmaContratoFotografia { get; set; }
        public string FechaPagoInicialFabricaFotografia { get; set; }
        public string FechaPagoInicialEquipoFotografia { get; set; }
        public string FechaConstruccionFotografia { get; set; }
        public string FechaSalidaFabricaFotografia { get; set; }
        public string FechaSalidaBuqueFotografia { get; set; }
        public string FechaLlegadaBuqueFotografia { get; set; }
        public string FechaPeriodoNacionalizacionFotografia { get; set; }
        public string FechaSalidaPuertoObraFotografia { get; set; }
        public string FechaInicioMontajeFotografia { get; set; }
        public string FechaEntregaSosoFotografia { get; set; }
        public string FechaConfiguracionFotografia { get; set; }
        public string FechaPeriodoPruebaFotografia { get; set; }
        public System.DateTime CartaPresentacion { get; set; }
        public System.DateTime FechaIngresoProduccion { get; set; }
        public System.DateTime EstatusConstruccion { get; set; }
        public System.DateTime IngresoDepartamentoIngMan { get; set; }
        public System.DateTime SolicitudPagoInicialFabrica { get; set; }
    }
}
