//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class requerimientos
    {
        public int Id { get; set; }
        public string Obra { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string GerenciaResponsable { get; set; }
        public string Tecnicos { get; set; }
        public string StatusRequerimiento { get; set; }
        public Nullable<System.DateTime> FechaCumplimientoSolicitud { get; set; }
        public string Descripcion { get; set; }
        public string AccionesEjecutadas { get; set; }
        public Nullable<int> obra_id { get; set; }
    }
}
