//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class sugerencias
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string AccionesTomadas { get; set; }
        public string AccionesRecomendadas { get; set; }
        public string GerenciaResponsable { get; set; }
        public Nullable<int> IdVenta { get; set; }
        public string Caracteristica { get; set; }
    }
}
