//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Web.Areas.Dap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensajesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ppgz.Web.Areas.Dap.MensajesResource", typeof(MensajesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta incorrecta.
        /// </summary>
        internal static string ERROR_Cuenta_IdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_Cuenta_IdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe el usuario.
        /// </summary>
        internal static string ERROR_CuentaManager_Crear_LoginExistente {
            get {
                return ResourceManager.GetString("ERROR_CuentaManager_Crear_LoginExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una cuenta maestra de proveedor registrada con este nombre.
        /// </summary>
        internal static string ERROR_CuentaManager_Crear_NombreProveedorExistente {
            get {
                return ResourceManager.GetString("ERROR_CuentaManager_Crear_NombreProveedorExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de proveedor Incorrecto.
        /// </summary>
        internal static string ERROR_CuentaManager_GetTipoByString {
            get {
                return ResourceManager.GetString("ERROR_CuentaManager_GetTipoByString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminar el SuperAdmin del sistema.
        /// </summary>
        internal static string ERROR_EliminarSuperAdmin {
            get {
                return ResourceManager.GetString("ERROR_EliminarSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminar el SuperUsuario..
        /// </summary>
        internal static string ERROR_EliminarSuperUsuario {
            get {
                return ResourceManager.GetString("ERROR_EliminarSuperUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_General.
        /// </summary>
        internal static string ERROR_General {
            get {
                return ResourceManager.GetString("ERROR_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido del mensaje es incorrecto.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_ContenidoIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_ContenidoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de caducidad debe ser superior a la fecha de publicación.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_Crear_FechaCadMayor {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_Crear_FechaCadMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de publicación incorrecta, debe ser mayor o igual a la fecha actual.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_FechaPublicacion {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_FechaPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviado a Incorrecto.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_GetEnviadoAByString {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_GetEnviadoAByString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje incorrecto.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_IdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_IdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje no existe.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_MensajeNoExiste {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_MensajeNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo de PDF es incorrecto.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_PdfIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_PdfIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ser un archivo PDF válido.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_PdfInvalido {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_PdfInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo incorrecto.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_TituloIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_TituloIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto no creado intente nuevamente.
        /// </summary>
        internal static string ERROR_ObrasContacto_CreadoIncorrectamente {
            get {
                return ResourceManager.GetString("ERROR_ObrasContacto_CreadoIncorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe agregar por lo menos 1 acceso al perfil.
        /// </summary>
        internal static string ERROR_PerfilNazan_AccesosRequeridos {
            get {
                return ResourceManager.GetString("ERROR_PerfilNazan_AccesosRequeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede editar o eliminar el perfil Maestro.
        /// </summary>
        internal static string ERROR_PerfilNazan_EditarEliminarMaestro {
            get {
                return ResourceManager.GetString("ERROR_PerfilNazan_EditarEliminarMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminar un perfil que tiene usuarios asociados.
        /// </summary>
        internal static string ERROR_PerfilNazan_EliminarConUsuarios {
            get {
                return ResourceManager.GetString("ERROR_PerfilNazan_EliminarConUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminar su propio usuario..
        /// </summary>
        internal static string ERROR_PerfilNazan_EliminarPropioUsuario {
            get {
                return ResourceManager.GetString("ERROR_PerfilNazan_EliminarPropioUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre para el perfil ya fue utilizado.
        /// </summary>
        internal static string ERROR_PerfilNazan_NombreExistente {
            get {
                return ResourceManager.GetString("ERROR_PerfilNazan_NombreExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil incorrecto.
        /// </summary>
        internal static string ERROR_PerfilNazan_PefilIdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_PerfilNazan_PefilIdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor incorrecto.
        /// </summary>
        internal static string ERROR_Proveedor_IdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_Proveedor_IdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Incorrecto.
        /// </summary>
        internal static string ERROR_UsuarioNazan_IdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_UsuarioNazan_IdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un usuario registrado con este login.
        /// </summary>
        internal static string ERROR_UsuarioNazan_LoginExistente {
            get {
                return ResourceManager.GetString("ERROR_UsuarioNazan_LoginExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta creada correctamente.
        /// </summary>
        internal static string INFO_Cuenta_CreadaCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Cuenta_CreadaCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envio actualizado correctamente.
        /// </summary>
        internal static string INFO_Envios_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Envios_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envio creado correctamente.
        /// </summary>
        internal static string INFO_Envios_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Envios_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envio eliminado correctamente.
        /// </summary>
        internal static string INFO_Envios_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Envios_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo actualizado correctamente.
        /// </summary>
        internal static string INFO_Equipos_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Equipos_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo creado correctamente.
        /// </summary>
        internal static string INFO_Equipos_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Equipos_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo eliminado correctamente.
        /// </summary>
        internal static string INFO_Equipos_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Equipos_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falla actualizada correctamente.
        /// </summary>
        internal static string INFO_Fallas_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Fallas_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falla creada correctamente.
        /// </summary>
        internal static string INFO_Fallas_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Fallas_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falla eliminada correctamente.
        /// </summary>
        internal static string INFO_Fallas_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Fallas_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion actualizada correctamente.
        /// </summary>
        internal static string INFO_GestionObras_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_GestionObras_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion creada correctamente.
        /// </summary>
        internal static string INFO_GestionObras_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_GestionObras_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion eliminada correctamente.
        /// </summary>
        internal static string INFO_GestionObras_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_GestionObras_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramienta actualizada correctamente.
        /// </summary>
        internal static string INFO_Herramientas_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Herramientas_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramienta creada correctamente.
        /// </summary>
        internal static string INFO_Herramientas_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Herramientas_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramienta eliminada correctamente.
        /// </summary>
        internal static string INFO_Herramientas_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Herramientas_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe actualizado correctamente.
        /// </summary>
        internal static string INFO_Informes_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Informes_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe creado correctamente.
        /// </summary>
        internal static string INFO_Informes_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Informes_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe eliminado correctamente.
        /// </summary>
        internal static string INFO_Informes_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Informes_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitdap actualizado correctamente.
        /// </summary>
        internal static string INFO_Kitdaps_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Kitdaps_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitdap creado correctamente.
        /// </summary>
        internal static string INFO_Kitdaps_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Kitdaps_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitdap eliminado correctamente.
        /// </summary>
        internal static string INFO_Kitdaps_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Kitdaps_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento Correctivo actualizado correctamente.
        /// </summary>
        internal static string INFO_MantenimientosCorrectivos_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_MantenimientosCorrectivos_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento Correctivo creado correctamente.
        /// </summary>
        internal static string INFO_MantenimientosCorrectivos_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_MantenimientosCorrectivos_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento Correctivo eliminado correctamente.
        /// </summary>
        internal static string INFO_MantenimientosCorrectivos_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_MantenimientosCorrectivos_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento Preventivo actualizado correctamente.
        /// </summary>
        internal static string INFO_MantenimientosPreventivos_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_MantenimientosPreventivos_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento Preventivo creado correctamente.
        /// </summary>
        internal static string INFO_MantenimientosPreventivos_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_MantenimientosPreventivos_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento Preventivo eliminado correctamente.
        /// </summary>
        internal static string INFO_MantenimientosPreventivos_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_MantenimientosPreventivos_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje actualizado correctamente.
        /// </summary>
        internal static string INFO_MensajesInstitucionales_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_MensajesInstitucionales_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje creado correctamente.
        /// </summary>
        internal static string INFO_MensajesInstitucionales_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_MensajesInstitucionales_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje eliminado correctamente.
        /// </summary>
        internal static string INFO_MensajesInstitucionales_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_MensajesInstitucionales_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obra actualizada correctamente.
        /// </summary>
        internal static string INFO_Obras_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Obras_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obra creada correctamente.
        /// </summary>
        internal static string INFO_Obras_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Obras_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obra eliminada correctamente.
        /// </summary>
        internal static string INFO_Obras_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Obras_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto creado correctamente.
        /// </summary>
        internal static string INFO_ObrasContacto_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_ObrasContacto_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil actualizado correctamente, los usuarios deben reiniciar la sesión.
        /// </summary>
        internal static string INFO_PerfilNazan_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_PerfilNazan_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil creado correctamente.
        /// </summary>
        internal static string INFO_PerfilNazan_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_PerfilNazan_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil eliminado correctamente.
        /// </summary>
        internal static string INFO_PerfilNazan_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_PerfilNazan_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previo actualizado correctamente.
        /// </summary>
        internal static string INFO_Previos_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Previos_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previo creado correctamente.
        /// </summary>
        internal static string INFO_Previos_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Previos_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previo eliminado correctamente.
        /// </summary>
        internal static string INFO_Previos_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Previos_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocolo actualizado correctamente.
        /// </summary>
        internal static string INFO_Protocolos_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Protocolos_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocolo creado correctamente.
        /// </summary>
        internal static string INFO_Protocolos_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Protocolos_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocolo eliminado correctamente.
        /// </summary>
        internal static string INFO_Protocolos_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Protocolos_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor asociado correctamente.
        /// </summary>
        internal static string INFO_Proveedor_AsociadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Proveedor_AsociadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor desasociado correctamente.
        /// </summary>
        internal static string INFO_Proveedor_DesAsocaidoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Proveedor_DesAsocaidoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor eliminado correctamente.
        /// </summary>
        internal static string INFO_Proveedor_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Proveedor_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requerimiento actualizado correctamente.
        /// </summary>
        internal static string INFO_Requerimientos_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Requerimientos_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requerimiento creado correctamente.
        /// </summary>
        internal static string INFO_Requerimientos_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Requerimientos_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requerimiento eliminado correctamente.
        /// </summary>
        internal static string INFO_Requerimientos_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Requerimientos_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugerencia actualizada correctamente.
        /// </summary>
        internal static string INFO_Sugerencias_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Sugerencias_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugerencia creada correctamente.
        /// </summary>
        internal static string INFO_Sugerencias_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Sugerencias_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugerencia eliminada correctamente.
        /// </summary>
        internal static string INFO_Sugerencias_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Sugerencias_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario actualizado correctamente.
        /// </summary>
        internal static string INFO_UsuarioNazan_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_UsuarioNazan_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario creado correctamente.
        /// </summary>
        internal static string INFO_UsuarioNazan_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_UsuarioNazan_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario eliminado correctamente.
        /// </summary>
        internal static string INFO_UsuarioNazan_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_UsuarioNazan_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta actualizada correctamente.
        /// </summary>
        internal static string INFO_Ventas_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Ventas_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta creada correctamente.
        /// </summary>
        internal static string INFO_Ventas_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Ventas_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta eliminada correctamente.
        /// </summary>
        internal static string INFO_Ventas_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Ventas_EliminadoCorrectamente", resourceCulture);
            }
        }
    }
}
